version: 2

models:
  - name: dim_categories
    columns:
      - name: category_id
        tests:
          - not_null
          - unique

  - name: dim_events
    columns:
      - name: event_id
        tests:
          - not_null
          - unique

  - name: dim_riders
    columns:
      - name: rider_id
        tests:
          - not_null
          - unique

  - name: dim_seasons
    columns:
      - name: season_id
        tests:
          - not_null
          - unique

  - name: dim_sessions
    columns:
      - name: session_id
        tests:
          - not_null
          - unique
      - name: event_id
        tests:
          - relationships:
              arguments:
                to: ref('dim_events')
                field: event_id
      - name: category_id
        tests:
          - relationships:
              arguments:
                to: ref('dim_categories')
                field: category_id

  - name: fact_event_grid
    columns:
      - name: event_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_events')
                field: event_id
      - name: category_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_categories')
                field: category_id
      - name: rider_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_riders')
                field: rider_id

  - name: fact_rider_season_stats
    columns:
      - name: rider_legacy_id
        tests:
          - not_null
      - name: season_year
        tests:
          - not_null

  - name: fact_session_classification
    columns:
      - name: session_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_sessions')
                field: session_id
      - name: rider_id
        tests:
          - not_null

  - name: fact_standings
    columns:
      - name: season_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_seasons')
                field: season_id
      - name: category_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_categories')
                field: category_id
      - name: rider_id
        tests:
          - not_null
